CC=g++
CFLAGS=-c -Wall
all: boardcover2

boardcover2:
	$(CC) boardcover2.cpp -o bin/boardcover2

tsp3:
	$(CC) tsp3.cpp -o bin/tsp3

copy_2d_array:
	$(CC) copy_2d_array.cpp -o bin/copy_2d_array

tsp2:
	$(CC) tsp2.cpp -o bin/tsp2

strjoin:
	$(CC) strjoin.cpp -o bin/strjoin

lunchbox:
	$(CC) lunchbox.cpp -o bin/lunchbox

matchorder:
	$(CC) matchorder.cpp -o bin/matchorder

maxsum: 
	$(CC) maxsum.cpp -o bin/maxsum


clean:
	rm -rf *.o bin/*
