all: search sort dynamic_array queue heap

heap: heap.cpp
	g++ -O2 -o heap heap.cpp

queue: queue.cpp
	g++ -O2 -o queue queue.cpp

search: search.cpp
	g++ -O2 -o search search.cpp

sort: sort.cpp
	g++ -O2 -o sort sort.cpp

dynamic_array: dynamic_array.cpp
	g++ -O2 -o dynamic_array dynamic_array.cpp
